
* History
** 2015: Offsets for 2015 run
** December 2015: Asked to evaluate possible re-alignment in the BI line and come out with a proposal
** 2016: Offsets for 2016 run. 
*** In the new csv files from GEODE, the longitudinal position was updated based on MADX, so all the offsets have changed, in most of the case slightly.
*** The requested re-alignment were:
**** VERTICAL:
***** BI.BPM40: move ENTRY and SORTIE point to -0.16 mm (from its current position of E=-2.04 mm and S=-2.28 mm)
***** BI.BPM50: move ENTRY and SORTIE point to 0.44 mm (from its current position of E=-2.52 mm and S=-1.27 mm)
**** RADIAL:
***** BI.QNO40: move ENTRY and SORTIE point to 2.81 mm (from its current position of E=3.18 mm and S=2.28 mm).
***** BI.BPM40: move ENTRY and SORTIE point to 0.53 mm (from its current position of E=-0.91 mm and S=-1.26 mm)
***** BI.BPM50: move ENTRY and SORTIE point to 0.53 mm (from its current position of E=-1.58 mm and S=-1.59 mm)
***** BI.QNO50: move ENTRY and SORTIE point to 0.65 mm (from its current position of E=-0.87 mm and S=-0.66 mm)

**** It turned out that BI.BPM50 could not be re-aligned. 
*** Tobias mentioned that the offset entered in GEODE with the date 14.12.2014 were incorrect and should not have been used. This was the case in 2015 for LT.QFN10. Now it is fixed...     
* Lines Definitions:
** LT  line start at the entry flange of LT.VVS10 and ends at the entry flange of LT.BHZ30
** LTB line start at the entry flange of LT.BHZ30 and ends at the entry flange of LTB.BHZ40
** BI3 line start at the entry flange of LTB.BHZ40 and ends at the entry flange of PSB.SMH1L1
*** Remember that all the calculation for GEODE are done in ring 3
*** The file how_to_calc_dist_BIxQNO60_BRxBHZ162.org reports the calculation to show how to pass from middle point of PSB.SMH1L1 to the middle point of PSB.BHZ162

* Scripts
** Just to generate some confusion in people there are 3 scripts depending from where the longitudinal positions are taken
*** align_withLonOffset.py is the DEFAULT script: longitudinal positions are from GEODE + longitudinal offsets

*** align.py: longitudinal positions are from GEODE

*** align_madx.py: longitudinal positions are from madx files from the 2014 repository, see http://project-ps-optics.web.cern.ch/project-PS-optics/cps/TransLines/Linac2-PSB/2014/

* Commands
** python align_withLonOffset.py -o rad -b > log/ltltbbi_offsets_rad
** python align_withLonOffset.py -o ver -b > log/ltltbbi_offsets_ver
** python align_withLonOffset.py -o lon
